# Generated by Django 3.2.12 on 2026-05-09 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_detallecompra_detalleventa_ordencompra_proveedor_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('descuento_fijo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_temporal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_temporal_inicio', models.DateField(blank=True, null=True)),
                ('descuento_temporal_fin', models.DateField(blank=True, null=True)),
                ('descuento_fidelidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('umbral_fidelidad', models.PositiveIntegerField(default=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'permissions': [('manage_clients', 'Puede gestionar clientes y descuentos')],
            },
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha'], 'permissions': [('manage_inventory', 'Puede gestionar inventario y stock')], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'permissions': [('manage_product_catalog', 'Puede gestionar catalogo de productos')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_venta'], 'permissions': [('register_sales', 'Puede registrar ventas'), ('generate_invoice_pdf', 'Puede generar facturas PDF')], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='HistorialDescuentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_descuento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(default='combinado', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_descuentos', to='inventario.cliente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_descuentos', to='inventario.venta')),
            ],
            options={
                'verbose_name': 'Historial de Descuento',
                'verbose_name_plural': 'Historial de Descuentos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='inventario.cliente'),
        ),
    ]
