# Generated by Django 3.2.12 on 2026-05-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20260509_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor principal que surte este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_surtidos', to='inventario.proveedor'),
        ),
    ]
