# Generated by Django 3.2.12 on 2026-05-27 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20260526_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'permissions': [('manage_product_catalog', 'Puede gestionar catalogo de productos'), ('ver_productos', 'Puede ver módulo de Productos'), ('ver_clientes', 'Puede ver módulo de Clientes'), ('ver_proveedores', 'Puede ver módulo de Proveedores'), ('ver_ventas', 'Puede ver módulo de Ventas'), ('ver_compras', 'Puede ver módulo de Compras'), ('ver_movimientos', 'Puede ver módulo de Movimientos'), ('ver_reportes', 'Puede ver módulo de Reportes')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
