# Generated by Django 3.2.12 on 2026-05-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_modulo_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio al que se compra este producto al proveedor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio al que se vende este producto al cliente', max_digits=10, null=True),
        ),
    ]
